### ISSUE TITLE
ANNOUNCEMENT: We're looking for volunteers to Alpha test a new Sesame feature

### ISSUE THREAD

**Issue by philwall2** [BranchMetrics/sesame_issues#118]
Hi all,

We're building a new feature called Contact Actions that expands what you can do with your contact shortcuts in Sesame.

**Here's the deal**

- We plan to charge for the feature but are hoping to get some volunteers to help us Alpha test it before then
- Alpha testers will get the feature for free :)
- Tell us 

if there are bugs and how we could improve it (shortcut requests, UI suggestions, etc.)

**How to join**

- Send me your email (phil@sesame.ninja or a DM is fine)
- I'll add you to the private Alpha in Google Play
- When we release the Alpha, you'll get the new version!

Thanks,

Phil & Steve

**Comment by XellossMetallium** [comment]
Hi, supposing this announcement was related to the contacts add-on, I just brought it and I wanted to point out that Plus messenger (Telegram client), which is supported, even if activated is not able to add the relevant link beside the contact. One thing that might be related to this issue is that I have two different account set up, and only one is private and synced and used for my contact list.
On a side note I do not find support for Facebook Messenger, the lite edition. This may be a feature request, but I think that if technically possible Facebook should be prioritised from the start (all official apps).
Thank you for the nice addon and please tell me if you prefer that I open a different issue for this matter.

**Comment by philwall2** [comment]
Hi @XellossMetallium we looked at Facebook and it doesn't seem possible, they don't have a method for us to get the shortcut data or open the links.

Plus should work... it's working on my test devices. If it's not giving you Plus shortcuts for your Contacts that means the Contacts DB isn't listing them. You can try rebooting or going into Sesame Settings > Contact Actions, that should trigger a refresh. If it's still not showing then I'm not sure what to do. If the data isn't in the ContactsDB there's not much we can do... :(

**Comment by Francesco270** [comment]
Hi, I've bought the Contact Actions however it doesn't work with Plus Messenger. I have the beta installed, maybe that's the reason? However it is recognised between the apps compatible in the settings. 
![Screenshot_2019-12-17-10-51-19-288_ninja sesame app edge](https://user-images.githubusercontent.com/57621306/70984883-87f25400-20bb-11ea-8509-dacd12feb212.png)
![Screenshot_2019-12-17-10-51-27-989_com android contacts](https://user-images.githubusercontent.com/57621306/70984896-8f196200-20bb-11ea-8f44-b9b9292d29e4.png)

**Comment by philwall2** [comment]
@Francesco270 there's a bug in Contact Actions. Sorry about that. It's out fault. We can't reproduce it so we added some more debug data tracking to the Beta. 

You can [join the Beta here](https://play.google.com/apps/testing/ninja.sesame.app.edge  
). Then go to Sesame Settings, Settings, Debug data, and "TAP TO SEND DEBUG DATA TO THE DEVELOPERS". Include the message "Contact actions".

That will give us a chance to see the problem and work on a fix. Sorry for the hassle. Thanks for reporting and helping.

**Comment by XellossMetallium** [comment]
@philwall2 hi, since this is now recognized as a bug I want to update my report: I tested two other telegram clients (bgram and graph messenger). They can be activated in the contacts plugin, but wont work nonetheless.
I'm going to activate the debug option. Thanks!

**Comment by Francesco270** [comment]
Done, thank you.
