### ISSUE TITLE
Remove app sources from the names of shortcuts

### ISSUE THREAD

**Issue by HunterArmstrong** [BranchMetrics/sesame_issues#177]
I just feel that having the name of the app where the shortcut came from is albatross. No other launcher would name their shortcuts "Spotify: Top hits of 2019" because the icon says it the most. And if there are shortcuts whom the names are the exact same, then maybe you can add the source in parenthesis or add a tag to the shortcut. Because it seems unnecessary.

**Comment by philwall2** [comment]
I get what you mean. The design logic is you can see the search term matched. Because Sesame will match first letters of words to return results quickly, we want to show the text input.

E.g. "Spotify: Top Hit of 2019" can be pulled up with "STH" and likely once you use it a couple times "ST", then just "S". To pull that off UI wise, we need to show users what the input we're matching is.

**Comment by HunterArmstrong** [comment]
Understood. Thank you for your time though. 😁
