### ISSUE TITLE
Small search icons misplaced 

### ISSUE THREAD

**Issue by ricardohnn** [BranchMetrics/sesame_issues#38]
Description:
Small search icons not centered

Details:
UI issue

Steps to reproduce:
- type any word
- mini search apps shows up for internal search
- clicking icon is not centered inside the box area

**Comment by philwall2** [comment]
Good catch and solid bug report!

We couldn't figure out how to get these alignments working dynamically. This has to do with the layout math of letting users change how many QuickSearch (mini) apps show. If you change the # of QuickSearch apps you have set, you'll see the rows adjust.

In order to both adjust the rows and center the icons, we'd have to build our own layout. This isn't impossible, it just takes time.

It retrospect we should go back and fix this.

**Comment by ricardohnn** [comment]
In my opinion it's pretty minor.
For a fast/temp "solution", i would remove the "hover" effect.
I know it's against UI patterns to not give the user a feedback, but again, the feedback itself would be the app opening after all... But I'm not sure if it's a feasible solution. Anyway i would set this as a minor.

**Comment by philwall2** [comment]
Cool. Appreciate the flexibility. We should fix this though. I made a new UI card #40 and am going to close this one.

Thanks again for the feedback. Hit us up anytime.
