### ISSUE TITLE
Use current launcher icon pack (icon cache)

### ISSUE THREAD

**Issue by threeFatCat** [BranchMetrics/sesame_issues#39]
Sesame app icons are not all themed, that is because some icons are not included in the icon pack. But with launchers like Nova, Hyperion, Lawnchair you can remedy that one by setting specifically a custom icon. But in Sesame I think there is no way to setup the unthemed icon, unless you will add that feature or use current launcher's icon cache.

**Comment by philwall2** [comment]
Hi. So you're looking to set a custom icon for an app, is that right?

If so, it's a good suggestion. At some point we plan to do this (and also let you edit labels).

To be honest, we've been doing a lot of UI work recently and haven't been building as many cool new shortcuts or data features as we'd like. Because of that, I'm going to mark this a low priority. But we rank our work by # of requests. If others ask for it (or thumbs up this), i'll move it up.

**Comment by philwall2** [comment]
@threeFatCat I made a new issue for UI requests and added this to it. #40
