### ISSUE TITLE
Add horizontal rotation

### ISSUE THREAD

**Issue by infinit7even** [BranchMetrics/sesame_issues#56]
Add horizontal rotation

![Screenshot_20190507-141403_Nova Launcher](https://user-images.githubusercontent.com/50268291/57298473-9793ce00-70d2-11e9-91ff-9cb31b5f2f2c.jpg)

so you can use the application event in landscape mode

**Comment by philwall2** [comment]
Landscape mode was added in the latest release. We only apply it to large screen sizes (giant phones and tablets) because there was a problem with the system keyboard covering up Sesame controls on smaller devices. Basically there's not enough room to do a decent landscape mode on normal/smaller size phones, so we have to restrict it or we'll be putting out a seemingly broken product. Sorry about that.
